-- Users table seeds here (Example)
INSERT INTO categories (category_name) VALUES ('back');
INSERT INTO categories (category_name) VALUES ('cardio');
INSERT INTO categories (category_name) VALUES ('chest');
INSERT INTO categories (category_name) VALUES ('lower_arms');
INSERT INTO categories (category_name) VALUES ('lower_legs');
INSERT INTO categories (category_name) VALUES ('neck');
INSERT INTO categories (category_name) VALUES ('shoulders');
INSERT INTO categories (category_name) VALUES ('upper_arms');
INSERT INTO categories (category_name) VALUES ('upper_legs');
INSERT INTO categories (category_name) VALUES ('waist');